### ISSUE TITLE
工单提交时，Emoji 表情引起的插入数据错误

### ISSUE THREAD

**Issue by CrazyNeil** [CrazyNeil/jntz-report#1]
[POST]: http://jntz-api.breiltech.com/ticket/store
Illuminate\Database\QueryException 
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x91\x8B\xE4\xBA...' for column 'content' at row 1 (SQL: insert into `jntz_ticket` (`user_id`, `ticket_state`, `content`, `attachment_1_url`, `attachment_2_url`, `created_at`) values (2, 1, 你好吗👋亟待解决的问题附近的经典款的规定。我的手机号码都没有啦。我的手机号是+8613的博文, storage/ticket/dHjouOtpzMc8xZ6vYGwT2FflyD21F1ujqVT3GP1Q.jpeg, , 2018-03-21 08:42:57))

**Comment by BrooksYang** [comment]
已解决

**Comment by BrooksYang** [comment]
解决方式：更换数据库字符集utf8-->utf8mb4      mb4的意思是most bytes 4，专门为兼容四个字节的。utf8mb4是向下兼容utf8的，所以即便修改了字段的字符集也不会影响线上数据。
